apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::575428171781:role/create-secret-from-secrets-manager-role
  name: account-to-access-secrets
  namespace: main
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: db-secrets-store
  namespace: main
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: account-to-access-secrets
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secrets
  labels:
    app: front
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: db-secrets-store
    kind: SecretStore
  target:
    name: database-secrets
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: database-secrets
      property: password
  - secretKey: dbname
    remoteRef:
      key: database-secrets
      property: dbname
  - secretKey: port
    remoteRef:
      key: database-secrets
      property: port
  - secretKey: host
    remoteRef:
      key: database-secrets
      property: host
  - secretKey: username
    remoteRef:
      key: database-secrets
      property: username
