apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-for-image-updater
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::575428171781:role/role-for-image-updater
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-image-updater
data:
  registries.conf: |
    registries:
      - name: ECR
        api_url: https://575428171781.dkr.ecr.ap-northeast-1.amazonaws.com
        prefix: 575428171781.dkr.ecr.ap-northeast-1.amazonaws.com
        credentials: ext:/app/scripts/ecr-login.sh
        credsexpire: 10h
  ecr-login.sh: |
    #!/bin/sh
    aws ecr --region ap-northeast-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
spec:
  template:
    spec:
      serviceAccountName: account-for-image-updater
      containers:
        - name: argocd-image-updater
          volumeMounts:
            - name: ecr-login-script
              mountPath: /app/scripts
      volumes:
        - name: ecr-login-script
          configMap:
            defaultMode: 0755
            items:
              - key: ecr-login.sh
                path: ecr-login.sh
            name: config-for-image-updater
            optional: true
