apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::575428171781:role/create-secret-from-secrets-manager-role
  name: account-to-access-secrets
  namespace: main
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: db-secrets-store
  namespace: main
spec:
  provider:
    aws:
      service: SecretsManager
      role: create-secret-from-secrets-manager-role
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: account-to-access-secrets
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret
  labels:
    app: front
  annotations:
    foo: bar
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: db-secrets-store
    kind: SecretStore
  target:
    name: database-secrets
    creationPolicy: 'Owner'
    deletionPolicy: "Delete"
  data:
  - secretKey: password
    remoteRef:
      key: database-secrets
      propertiy: 
  - secretKey: dbname
  - secretKey: port
  - secretKey: host
  - secretKey: username
