namespace: main
fullnameOverride: ""
nameOverride: ""
domainName: mycdk-myk8s-example.com
clusterName: eks-cluster
front:
  replicaCount: 2
  imageTag: a6a4391ef7b8dfafedee085c8f33375b91908920
  resources:
    app:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 600m
        memory: 512Mi
    web:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
externalDns:
  replicaCount: 2
  imageTag: v0.12.2
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 600m
      memory: 512Mi
dbSecrets:
  - envName: DB_HOST
    secretName: database-secrets
    key: host
  - envName: DB_PORT
    secretName: database-secrets
    key: port
  - envName: DB_USER
    secretName: database-secrets
    key: username
  - envName: DB_PASSWORD
    secretName: database-secrets
    key: password
  - envName: DB_NAME
    secretName: database-secrets
    key: dbname
