apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: myproject
  source:
    repoURL: https://github.com/k-akari/myk8s
    path: ./dbsecrets/overlays/production
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
