apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/write-back-target: kustomization:../../main/overlays/production
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: app=575428171781.dkr.ecr.ap-northeast-1.amazonaws.com/eks-app,web=575428171781.dkr.ecr.ap-northeast-1.amazonaws.com/eks-web
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/web.update-strategy: semver
spec:
  project: myproject
  source:
    repoURL: https://github.com/k-akari/myk8s
    path: ./main/overlays/production/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
