apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secretsmanager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: secretsmanager
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: myproject
  source:
    repoURL: https://github.com/k-akari/myk8s.git
    path: secretsmanager/
    targetRevision: main
    helm:
      releaseName: myk8s
      version: v3
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: secretsmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
