main:
  helmVersion: v3
  targetRevision: main
  namespace: main
  projectName: myproject
prometheus:
  targetRevision: 39.11.0
  namespace: monitoring
  projectName: monitoring
keda:
  targetRevision: 2.8.2
  namespace: keda
argo:
  projectName: default
  targetRevision: 2.20.0
  namespace: argocd
