apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: db-migrator
        image: 575428171781.dkr.ecr.ap-northeast-1.amazonaws.com/eks-migration:v0.0.1
        command:
        - "/bin/ash"
        args:
        - "-c"
        - "/app/cmd"
      restartPolicy: Never
  backoffLimit: 2
