apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: main
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: db-secrets-store
    kind: SecretStore
  target:
    name: database-secrets
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: database-secrets
      property: password
  - secretKey: dbname
    remoteRef:
      key: database-secrets
      property: dbname
  - secretKey: port
    remoteRef:
      key: database-secrets
      property: port
  - secretKey: host
    remoteRef:
      key: database-secrets
      property: host
  - secretKey: username
    remoteRef:
      key: database-secrets
      property: username
