apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "secretsmanager.fullname" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "secretsmanager.fullname" . }}
