apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: db-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: account-to-access-secrets
