apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "secretsmanager.fullname" . }}
  labels:
    {{- include "secretsmanager.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "secretsmanager.fullname" . }}
