apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secretsmanager.fullname" . }}
  labels:
    {{- include "secretsmanager.labels" . | nindent 4 }}
    app.kubernetes.io/component: account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccount }}:role/{{ .Values.roleName }}
