apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secretsmanager.fullname" . }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccount }}:role/create-secret-from-secrets-manager-role
