apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: {{ .Values.prometheus.projectName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.keda.namespace }}
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: {{ .Values.keda.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
