apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: main
spec:
  project: myproject
  source:
    repoURL: https://github.com/k-akari/myk8s.git
    path: main/
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: myk8s
      version: {{ .Values.helmVersion }}
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
