apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: {{ .Values.prometheus.projectName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.prometheus.namespace }}
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-{{ .Values.prometheus.targetRevision }}
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: {{ .Values.prometheus.projectName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.prometheus.namespace }}
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: {{ .Values.prometheus.targetRevision }}
    helm:
      skipCrds: true
      values: |-
        #Snip the values
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
