apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemonitors
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  labels:
    app.kubernetes.io/name: servicemonitors
spec:
  project: {{ .Values.prometheus.projectName }}
  source:
    repoURL: https://github.com/k-akari/myk8s.git
    path: servicemonitors/
    targetRevision: {{ .Values.main.targetRevision }}
    helm:
      releaseName: myk8s
      version: {{ .Values.main.helmVersion }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.prometheus.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
