apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "externalDns.fullname" . }}
  labels:
    {{- include "externalDns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.externalDns.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "externalDns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "externalDns.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "externalDns.fullname" . }}
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:{{ .Values.externalDns.imageTag }}
        args:
        - --source=ingress
        - --source=service
        - --domain-filter={{ .Values.domainName }}
        - --provider=aws
        - --policy=sync
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id={{ .Values.clusterName }}
        resources:
          {{- toYaml .Values.externalDns.resources | nindent 10 }}
      securityContext:
        fsGroup: 65534
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.front.replicaCount }}
  selector:
    matchLabels:
      {{- include "front.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "front.fullname" . }}
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        {{- include "front.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: app
        image: 575428171781.dkr.ecr.ap-northeast-1.amazonaws.com/eks-app:{{ .Values.front.imageTag }}
        resources:
          {{- toYaml .Values.front.resources.app | nindent 10 }}
        ports:
        - containerPort: 8080
        env:
        {{- range .Values.dbSecrets }}
        - name: {{ .envName }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .key }}
        {{- end }}
      - name: web
        image: 575428171781.dkr.ecr.ap-northeast-1.amazonaws.com/eks-web:{{ .Values.front.imageTag }}
        resources:
          {{- toYaml .Values.front.resources.web | nindent 10 }}
        ports: 
        - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "main.name" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ include "externalDns.instanceLabel" . }}
              topologyKey: topology.kubernetes.io/zone
