apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "front.fullname" . }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "front.labels" . | nindent 4 }}
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrator
        image: 575428171781.dkr.ecr.ap-northeast-1.amazonaws.com/eks-migration:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "600m"
        command:
        - "/bin/ash"
        args:
        - "-c"
        - "/app/cmd"
        env:
        {{- range .Values.dbSecrets }}
        - name: {{ .envName }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .key }}
        {{- end -}}
